version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: brokebuy-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: brokebuy
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - brokebuy-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # FastAPI Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brokebuy-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - brokebuy-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Node.js Scraper
  scraper:
    build:
      context: ../SRM-Academia-Scraper-node-main/server
      dockerfile: Dockerfile
    container_name: brokebuy-scraper
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    networks:
      - brokebuy-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # React Frontend
  frontend:
    build:
      context: ../proj_BrokeBuy_frontend/srm-brokebuy-vibe
      dockerfile: Dockerfile
    container_name: brokebuy-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
      - scraper
    networks:
      - brokebuy-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:
    driver: local

networks:
  brokebuy-network:
    driver: bridge
